### PR TITLE
Add proofread action CI

### PR DESCRIPTION
**Pull request by stavares843**
This PR includes the following:
- CI that verifies both grammar and typos in the PR and adds comments

Captura de ecrã 2023-03-20, às 19 24 04

More info regarding the CI [here](https://github.com/awreck/proofread-action)

### CODE REVIEW

**Comment by verdverm** [comment]
A few points here:

1. We want something we can run locally too, to avoid sending commits off to actions because of laziness
2. Where is the source for this action?
3. hof's GHA are defined as CUE, with the Yaml generated

**Comment by stavares843** [comment]
> We want something we can run locally too, to avoid sending commits off to actions because of laziness

I can look into something in a pre-commit hook as well

> Where is the source for this action?

it's [here](https://github.com/awreck/proofread-action), i've added in the description as well 🔨 

> hof's GHA are defined as CUE, with the Yaml generated

yes in this case this action only runs in the .md files

**Comment by verdverm** [comment]
This is not a priority compared to content.

> > hof's GHA are defined as CUE, with the Yaml generated
> yes in this case this action only runs in the .md files

I mean the actual action workflow is written as CUE, not Yaml (see the ci/gha directory)

**Comment by verdverm** [comment]
Under-the-hood, this is using LanguageTool

- https://github.com/awreck/proofread-action/blob/main/index.js#L31
- https://languagetool.org/proofreading-api

**Comment by stavares843** [comment]
Got it, will close for now! I added because it was a 5m task 😄 thanks for taking a look! 🔨

**Comment by verdverm** [comment]
I don't think this action is usable based on: https://dev.languagetool.org/public-http-api

We have much more than 20 pages, other limits seem problematic.

This action seems to violate their TOS

**Pull request closed without merging**
